"""Rename listmodel table to lists and item table to items

Revision ID: abaa41c6b81f
Revises: 40bfde2921de
Create Date: 2026-01-30 14:21:47.753318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abaa41c6b81f"
down_revision: Union[str, Sequence[str], None] = "40bfde2921de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable foreign key constraints
    connection = op.get_bind()
    connection.execute(sa.text("PRAGMA foreign_keys = ON;"))

    # Rename listmodel table to lists
    op.rename_table("listmodel", "lists")
    # Rename item table to items
    op.rename_table("item", "items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable foreign key constraints
    connection = op.get_bind()
    connection.execute(sa.text("PRAGMA foreign_keys = ON;"))

    # Rename lists table back to listmodel
    op.rename_table("lists", "listmodel")
    # Rename items table back to item
    op.rename_table("items", "item")
    # ### end Alembic commands ###
